openapi: 3.0.0
info:
  version: 1.0.0
  title: Partner Integrations
paths:
  /merchant:
    get:
      summary: "Get a Merchant record"
      operationId: merchant_read
      tags:
        - Platform
      responses:
        "200":
          description: "The created resource and its control webhooks"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Merchant"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /checkout:
    post:
      summary: "Generate a Marketplace Checkout"
      operationId: checkout_create
      tags:
        - Checkout
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderRequest"
      responses:
        "200":
          description: "The created resource and its control webhooks"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    OrderRequest:
      type: object
      properties:
        merchant_reference:
          type: string
        callback_url:
          type: object
          properties:
            success:
              type: string
            error:
              type: string
            cancel:
              type: string
            default:
              type: string
        order:
          $ref: "#/components/schemas/Order"
    OrderResponse:
      type: object
      properties:
        order_reference:
          type: string
        checkout_url:
          type: string
        customer_reference:
          type: string
        order:
          $ref: "#/components/schemas/Order"
    Merchant:
      type: object
      required:
        - code
      properties:
        id:
          type: number
        code:
          type: string
        name:
          type: string
        base_url:
          type: string
        features:
          type: array
          items:
            $ref: "#/components/schemas/MarketFeature"
    Customer:
      type: object
      required:
        - first_name
        - last_name
        - email
        - phone
        - birthdate
      properties:
        id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
          type: string
        birthdate:
          type: string
        email:
          type: string
        phone:
          type: string
        verification:
          type: string

        tag:
          type: string
    Address:
      type: object
      required:
        - zipcode
        - address1
        - city
        - country
      properties:
        zipcode:
          type: integer
          format: int64
        address1:
          type: string
        address2:
          type: string
        city:
          type: string
        country:
          type: string
        additional_info:
          type: string
    Order:
      type: object
      required:
        - shipping_address
        - customer
        - items
        - order_mode
      properties:
        order_mode:
          type: string
        order_number:
          type: string
        shipping_address:
          $ref: "#/components/schemas/Address"
        billing_address:
          $ref: "#/components/schemas/Address"
        customer:
          $ref: "#/components/schemas/Customer"
        payment:
          $ref: "#/components/schemas/Payment"
        adjustment:
          $ref: "#/components/schemas/Adjustment"
        items:
          $ref: "#/components/schemas/LineItem"
        total:
          type: number
          format: currency
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Adjustment:
      type: object
      properties:
        adjustment_type:
          type: string
        amount:
          type: number
          format: currency
        applied:
          type: boolean
          default: true
    Payment:
      type: object
      properties:
        payment_type:
          type: string
        payment_reference:
          type: string
          format: uuid
    LineItem:
      oneOf:
        - $ref: "#/components/schemas/FlexLineItem"
        - $ref: "#/components/schemas/MixLineItem"
    FlexLineItem:
      type: object
      required:
        - product_sku
        - variant_sku
        - rental_plan_id
      properties:
        product_sku:
          type: string
        variant_sku:
          type: string
        quantity:
          type: integer
          format: int32
          default: 1
        rental_plan_id:
          type: integer
          format: int64
    MixLineItem:
      type: object
      required:
        - product_sku
        - variant_sku
        - category_id
        - subcategory_id
      properties:
        product_sku:
          type: string
        variant_sku:
          type: string
        category_id:
          type: integer
          format: int32
        subcategory_id:
          type: integer
          format: int32
    MarketFeature:
      type: object
      properties:
        merchant_id:
          type: integer
          format: int16
        feature_id:
          type: integer
          format: int32
        active:
          type: boolean
          default: false
        config:
          type: object
          properties:
            id:
              type: integer
            value:
              type: string
